### ISSUE TITLE
Research APIs and Permissions for App. 

### ISSUE THREAD

**Issue by sdstaley** [sdstaley/UT9_HERMES#12]

**Comment by sudoaj** [comment]
**[Permissions]**
https://developer.android.com/guide/topics/permissions/overview!

[Screen Shot 2021-02-11 at 9.42.45 AM.png]

(https://images.zenhubusercontent.com/601e37b989d0a4ef8e430688/cd510926-e215-4808-bdcd-aa4c63775286)

**Comment by sudoaj** [comment]
**[Permissions]**
https://developer.android.com/training/permissions/requesting
