### ISSUE TITLE
Figure out which version of firebase to use for app

### ISSUE THREAD

**Issue by sdstaley** [sdstaley/UT9_HERMES#14]

**Comment by sudoaj** [comment]
Cloud Firestore is Firebase's newest database for mobile app development.

**Comment by sudoaj** [comment]
https://firebase.google.com/docs/database/rtdb-vs-firestore

**Comment by sudoaj** [comment]
VERSION TO USE: 22.1.0

How to add to android studio: https://firebase.google.com/docs/firestore/quickstart
