### ISSUE TITLE
Start UI Research for App

### ISSUE THREAD

**Issue by sdstaley** [sdstaley/UT9_HERMES#15]

**Comment by niraliparikh23** [comment]
1. Need to discuss a color scheme, elements to put on screens, and layout. 
2. Find message app templates after #1 is discussed and figured out. 
3. Change template to color scheme and to match layout and elements needed for the app.

**Comment by niraliparikh23** [comment]
1. Draw Layout
2.Blue & White color scheme with Black font. Elements/Layout on Discord. 
3. Download templates
4. Next thing to do.
