### ISSUE TITLE
conceptualize/create UML sequence diagrams

### ISSUE THREAD

**Issue by mghebre20** [sdstaley/UT9_HERMES#34]

**Comment by niraliparikh23** [comment]
[https://app.zenhub.com/files/333971499/c2a0d289-70c6-4c75-8d22-276ad9795953/download](https://app.zenhub.com/files/333971499/c2a0d289-70c6-4c75-8d22-276ad9795953/download)

[https://app.zenhub.com/files/333971499/d35b6ec8-6b13-4893-96eb-d8b760c526d6/download](https://app.zenhub.com/files/333971499/d35b6ec8-6b13-4893-96eb-d8b760c526d6/download)
